**실습 코드**

In [ ]:
import pandas as pd#판다스 추가
import numpy as np#넘파이 추가

2.1) Series와 DataFrame
- Series: 레이블을 가지는 1차원 배열
- DataFrame: 레이블을 갖는 행과 열을 갖는 2차원 배열(index,key,value들로 구성된다.)

2.2) Series 만들기

In [ ]:
floatscore=pd.Series([77,23,1.2,7,54,7])# Series는 동일한 유형의 데이터를 저장한다.이경우 모두 float로 인식
print(floatscore)
intscore=pd.Series([2,3,4,5,6,7])#int 로 인식
print(intscore)

0    77.0
1    23.0
2     1.2
3     7.0
4    54.0
5     7.0
dtype: float64
0    2
1    3
2    4
3    5
4    6
5    7
dtype: int64


In [ ]:
print(pd.Series([2,3,4],index=['a','b','c']))

a    2
b    3
c    4
dtype: int64


2.3) DataFrame 만들기

In [ ]:
arr=np.arange(20).reshape(5,4)
print(arr)
df=pd.DataFrame(arr)
print(df)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19


In [ ]:
print(pd.DataFrame(arr,index=['a','b','c','d','e'],columns=['A','B','C','D']))
k=pd.DataFrame(arr,index=['a','b','c','d','e'],columns=['A','B','C','D'])#print에 넣은것과 아닌것 차이

    A   B   C   D
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15
e  16  17  18  19


In [ ]:
df=pd.DataFrame({'name':['신성현','김땡땡','이땡땡','조땡땡'],'score':[10,20,30,40],'dept':['com','eng','math','soc']},index=[1,2,3,4])#딕셔너리의 키->DataFrame key이고 DataFrame의 열은 서로 다른 자료형을 가진다.
print(df)
df2=pd.DataFrame({'int':intscore,'index':floatscore})#이렇게 Series를 합칠수도 있다.
print(df2)

  name  score  dept
1  신성현     10   com
2  김땡땡     20   eng
3  이땡땡     30  math
4  조땡땡     40   soc
   int  index
0    2   77.0
1    3   23.0
2    4    1.2
3    5    7.0
4    6   54.0
5    7    7.0


2.4) csv활용
- 판다스가 제공하는 read_csv()함수 사용

In [ ]:
df=pd.read_csv('mobile.csv')
df

Brand   Color  price
0  Samsung   Black    100
1       LG    Gold     70
2    Apple  Silver    150
3    Apple    Gray    120

In [ ]:
df=pd.read_csv('mobile.csv',index_col=0)#index_col은 인덱스로 사용할 열을 지정한다.첫번째 열이 index가 되었다.
print(df)
df2=pd.read_csv('mobile.csv',index_col='Color')#이름으로도 지정가능하다.
print(df2)
#행을 키값으로 지정하려면??

          Color  price
Brand                 
Samsung   Black    100
LG         Gold     70
Apple    Silver    150
Apple      Gray    120
          Brand  price
Color                 
Black   Samsung    100
Gold         LG     70
Silver    Apple    150
Gray      Apple    120


3) 판다스 데이터 확인

In [ ]:
df=pd.read_csv('weather.csv')
df

date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
df.shape

(3653, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       3653 non-null   object 
 1   temp       3653 non-null   float64
 2   max_wind   3649 non-null   float64
 3   mean_wind  3647 non-null   float64
dtypes: float64(3), object(1)
memory usage: 114.3+ KB


In [ ]:
print(df.head())#지정안하면 5개
print(df.tail(4))

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6
            date  temp  max_wind  mean_wind
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5


In [ ]:
print(df.index)#인덱스(행이름)반환
print(df.columns)#해당 데이터프레임을 구성하는 컬럼명 확인

RangeIndex(start=0, stop=3653, step=1)
Index(['date', 'temp', 'max_wind', 'mean_wind'], dtype='object')


In [ ]:
print(df.describe())
print('mean: {}'.format(df['temp'].mean()))#각자 따로 사용할 수도 있다.

              temp     max_wind    mean_wind
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000
mean: 12.942102381604162


In [ ]:
print(df.sort_values(by='max_wind'))#DataFrame.sort_value(by=['정렬변수1','정렬변수2',...],ascending=False,inplace=True)형식이다. 내림차순이면 ascending=false사용
print(df.sort_values(by='max_wind',ascending=False))#내림차순 정렬

            date  temp  max_wind  mean_wind
1514  2014-09-23  20.7       2.0        1.0
1134  2013-09-08  20.4       2.1        0.8
421   2011-09-26  18.7       2.1        0.3
1512  2014-09-21  20.4       2.2        1.2
1005  2013-05-02   7.1       2.2        0.8
...          ...   ...       ...        ...
2988  2018-10-06  19.4      26.0        7.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]
            date  temp  max_wind  mean_wind
2988  2018-10-06  19.4      26.0        7.0
3340  2019-09-23  15.0      25.8       11.0
1850  2015-08-25  20.1      25.3       14.9
3339  2019-09-22  15.7      23.1       11.9
1851  2015-08-26  17.4      22.6        8.1
...          ...   ...       ...        ...
1514  2014-09-23  20.7       2.0        1.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2

In [ ]:
bank=pd.read_csv('bank.csv')
print(bank)#범주형 변수의 빈도분석 결과를 출력한다.
print(bank['job'].value_counts())#내림차순
print(bank['job'].value_counts(ascending=True))#오름차순

                job  education  balance  duration    y
0        management   tertiary     2143       261   no
1        technician  secondary      265       348   no
2       blue-collar  secondary       -7       365   no
3        technician  secondary       -3      1666   no
4        technician  secondary     -103       145   no
...             ...        ...      ...       ...  ...
7229       services  secondary      199       173   no
7230  self-employed   tertiary      159       449  yes
7231     management   tertiary      138       162   no
7232     management   tertiary     1428       333   no
7233     technician  secondary      505       386  yes

[7234 rows x 5 columns]
job
management       1560
blue-collar      1499
technician       1206
admin.            834
services          661
retired           351
self-employed     256
entrepreneur      239
unemployed        223
housemaid         208
student           153
Name: count, dtype: int64
job
student           153
housemaid        

In [ ]:
bank['job'].unique()#'job' 이 어떤 구성으로 이루어져 있는지 확인

array(['management', 'technician', 'blue-collar', 'retired', 'services',
       'admin.', 'entrepreneur', 'self-employed', 'unemployed', 'student',
       nan, 'housemaid'], dtype=object)

4) 판다스 데이터 선택

In [ ]:
df

date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
#단일 컬럼 선택하기
print(df['temp'])
print(df.temp)#둘다 사용이 가능하다.

0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ... 
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64
0       28.7
1       25.2
2       22.1
3       25.3
4       27.2
        ... 
3648    22.1
3649    21.9
3650    21.6
3651    22.9
3652    25.7
Name: temp, Length: 3653, dtype: float64


In [ ]:
#여러 컬럼 선택하기
print(df[['temp','date']])#추출할 열 이름을 목록에 저장한 다음[]에 전달하면 DatFrame에서 여러 열을 선택한다.
print(df.loc[:,['date','temp']])#열 이름을 사용하여 열을 선택하는 경우 loc()을 사용한다.
print(df.iloc[:,[0,1]])#열 인덱스 사용시 iloc()사용

      temp        date
0     28.7  2010-08-01
1     25.2  2010-08-02
2     22.1  2010-08-03
3     25.3  2010-08-04
4     27.2  2010-08-05
...    ...         ...
3648  22.1  2020-07-27
3649  21.9  2020-07-28
3650  21.6  2020-07-29
3651  22.9  2020-07-30
3652  25.7  2020-07-31

[3653 rows x 2 columns]
            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]
            date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]


In [ ]:
#특정 행 범위 선택하기
print(df[0:3])

         date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9


In [ ]:
#레이블로 선택하기(df.loc)
df.index=df['date']
print(df.loc['2010-08-01',['temp','mean_wind']])
print()
#위치로 선택하기
print(df.iloc[3])

temp         28.7
mean_wind     3.4
Name: 2010-08-01, dtype: object

date         2010-08-04
temp               25.3
max_wind            6.6
mean_wind           4.2
Name: 2010-08-04, dtype: object


In [ ]:
df.reset_index(drop=True,inplace=True)
df

date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
#특정 행과 열 선택:슬라이싱
df.iloc[1:3,0:2]

date  temp
1  2010-08-02  25.2
2  2010-08-03  22.1

In [ ]:
#불 인덱싱
w=df.temp>=30 #30보다 크면 true를 저장한다.
df[w]

date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6
1104  2013-08-09  30.6       9.9        6.4
1105  2013-08-10  30.6       7.4        3.8
2913  2018-07-23  30.5       6.5        1.6
2925  2018-08-04  30.3       5.8        3.0

In [ ]:
w=df.temp==df.temp.max()
df[w]#가장 더웠던 날의 정보

date  temp  max_wind  mean_wind
1103  2013-08-08  31.3       7.8        4.6

In [ ]:
w=(df['temp']>=30)&(df['max_wind']>=9)
print(df[w])
k=(df.temp>=30)&(df.max_wind>=9)
print(df[k])#조건이 2개 이상이면()로 묶는다.

            date  temp  max_wind  mean_wind
1104  2013-08-09  30.6       9.9        6.4
            date  temp  max_wind  mean_wind
1104  2013-08-09  30.6       9.9        6.4


5) 판다스 결측데이터 처리
- 판다스는 누락된 데이터를 표시할 때 NaN으로 표시하고 연산에는 포함되지 않는다.

In [ ]:
#결측데이터 확인
print(df[df.mean_wind.isna()])#isna()함수는 값이 nan일때 True, 그렇지 않으면 False가 된다.
print(df[df.mean_wind.isnull()])#isnull도 가능하다.

            date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
1694  2015-03-22  10.1      11.6        NaN
1704  2015-04-01   7.3      12.1        NaN
3182  2019-04-18  15.7      11.7        NaN
            date  temp  max_wind  mean_wind
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
1694  2015-03-22  10.1      11.6        NaN
1704  2015-04-01   7.3      12.1        NaN
3182  2019-04-18  15.7      11.7        NaN


In [ ]:
#결측데이터 개수 확인:컬럼별 결측데이터 개수 확인
print(df.isnull().sum())#isnull()함수가 결측데이터이면 True값을 반환하고, 유효한 데이터가 존재하면 false를 반환한다. notnull()은 반대
print()
print(df.isna().sum())

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64


- 결측데이터 삭제하기
  - dropna()함수 이용하여 삭제
  - 매개변수
    - axis: 축을 행 또는 열로 결정한다, 0,index-> 누락값 포함 행 삭제 1,columns-> 누락값포함 열 삭제. 기본적으로 0이다.
    - how: any->null값이 있는경우 행 또는 열 삭제한다. all->모든 값이 누락된 경우 행 또는 열을 삭제
    - inplace: True로 설정하면 호출자 DataFrame을 변경하는 부울 값 기본적으로는 False

In [ ]:
#결측데이터가 있는 행 삭제 후 확인
df2=df.dropna()
df2.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [ ]:
#결측데이터 대체:평균값으로 대체
df.index=df['date']
df.drop('date',axis=1,inplace=True)
df.fillna(df.mean(),inplace=True)
df.isnull().sum()

temp         0
max_wind     0
mean_wind    0
dtype: int64

6) 판다스 데이터 가공

In [ ]:
dust=pd.read_excel('dust1.xlsx')
dust.head()

지역     망   측정소코드 측정소명        측정일시    SO2   CO     O3    NO2  PM10  \
0  서울 송파구  도시대기  111273  송파구  2021040101  0.004  1.0  0.002  0.066    50   
1  서울 송파구  도시대기  111273  송파구  2021040102  0.004  0.8  0.002  0.058    48   
2  서울 송파구  도시대기  111273  송파구  2021040103  0.004  0.8  0.002  0.055    44   
3  서울 송파구  도시대기  111273  송파구  2021040104  0.003  0.8  0.002  0.055    40   
4  서울 송파구  도시대기  111273  송파구  2021040105  0.004  0.8  0.002  0.053    38   

   PM25                주소  
0    18  서울 송파구 백제고분로 236  
1    20  서울 송파구 백제고분로 236  
2    20  서울 송파구 백제고분로 236  
3    20  서울 송파구 백제고분로 236  
4    17  서울 송파구 백제고분로 236

In [ ]:
dust=dust.drop(['지역','망','측정소코드'],axis=1)#열을 삭제하려면 반드시 axis=1써주어야 한다. 기본값은 0
dust.head()

측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236

In [ ]:
dust['city']='서울'
dust.head()

측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소  \
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236   
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236   
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236   
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236   
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236   

  city  
0   서울  
1   서울  
2   서울  
3   서울  
4   서울

In [ ]:
dust.rename(columns={'측정소명':'name', '측정일시':'date','주소':'addr'},inplace=True)#데이터 이름 변환
dust.columns

Index(['name', 'date', 'SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', 'addr',
       'city'],
      dtype='object')

In [ ]:
#데이터 형변환
dust.dtypes

name     object
date      int64
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr     object
city     object
dtype: object

In [ ]:
dust['date']=dust['date'].astype(str)
dust['date']=dust['date'].str.slice(0,8)
dust.dtypes

name     object
date     object
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr     object
city     object
dtype: object

In [ ]:
dust['date']=pd.to_datetime(dust['date'])
dust.dtypes

name            object
date    datetime64[ns]
SO2            float64
CO             float64
O3             float64
NO2            float64
PM10             int64
PM25             int64
addr            object
city            object
dtype: object

In [ ]:
dust['year']=dust['date'].dt.year
dust['month']=dust['date'].dt.month
dust['day']=dust['date'].dt.day
dust.head()

name       date    SO2   CO     O3    NO2  PM10  PM25              addr  \
0  송파구 2021-04-01  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236   
1  송파구 2021-04-01  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236   
2  송파구 2021-04-01  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236   
3  송파구 2021-04-01  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236   
4  송파구 2021-04-01  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236   

  city  year  month  day  
0   서울  2021      4    1  
1   서울  2021      4    1  
2   서울  2021      4    1  
3   서울  2021      4    1  
4   서울  2021      4    1

In [ ]:
#데이터 병합하기
#pd.merge(df_left,df_right,how='inner',on=None)
s1=pd.read_excel('nation.xlsx')
s2=pd.read_excel('code.xlsx')
print(s1)
print(s2)
pd.merge(s1,s2, on='국적코드')

  국적코드  성별    입국객수    증가수
0  A01  남성  125000   8000
1  A01  여성  130000  10000
2  A05  남성     300     10
3  A05  여성     200     50
4  A06  남성  158912  24486
5  A06  여성  325000  63466
  국적코드  국적명
0  A01  필리핀
1  A02   일본
2  A03   미국
3  A04   중국
4  A05   호주
5  A06  베트남
6  A07  스위스
7  A99   기타


국적코드  성별    입국객수    증가수  국적명
0  A01  남성  125000   8000  필리핀
1  A01  여성  130000  10000  필리핀
2  A05  남성     300     10   호주
3  A05  여성     200     50   호주
4  A06  남성  158912  24486  베트남
5  A06  여성  325000  63466  베트남

7) 판다스 데이터 그룹핑
- 데이터 그룹핑은 데이터를 특정한 값에 기반에 묶는 기능으로 groupby()함수를 사용해 통계량을 요약한다.
- 통계량 관련 함수에는 mean,std(표준편차),var(분산),max,min,mode(최빈값) 등이 있다.

In [ ]:
#한열을 기준으로 그룹화
s1=pd.read_excel('nation.xlsx')
s2=s1.drop(['성별'],axis=1)
s2.groupby('국적코드').sum()

입국객수    증가수
국적코드               
A01   255000  18000
A05      500     60
A06   483912  87952

In [ ]:
#여러열을 기준으로 그룹화->여러열을 그룹으로 묶어서 계층적인 인덱스를 구성한다.
s1=pd.read_excel('nation.xlsx')
s1.groupby(['국적코드','성별']).sum()

입국객수    증가수
국적코드 성별               
A01  남성  125000   8000
     여성  130000  10000
A05  남성     300     10
     여성     200     50
A06  남성  158912  24486
     여성  325000  63466

**연습 문제**

연습 1)

In [ ]:
#1
temp=pd.read_csv('temp.csv')
print(temp)
print('------------------------------------------------------------------')
#2
print(temp[['최고기온(°C)','최저기온(°C)']])
print('------------------------------------------------------------------')
#3
w=temp['평균기온(°C)']>=20
print(temp[w])
print('------------------------------------------------------------------')
#4
w=temp['최고기온(°C)']==temp['최고기온(°C)'].max()
maxtemp=temp[w]
maxtemp[['평균기온(°C)','최저기온(°C)','최고기온(°C)']]

      지점 지점명          일시  평균기온(°C)  최저기온(°C)  최저기온 시각(hhmi)  최고기온(°C)  \
0    108  서울  2003-01-01      -4.7      -7.1           2231      -1.0   
1    108  서울  2003-01-02      -4.3      -9.2            447       0.0   
2    108  서울  2003-01-03      -3.6      -6.8           2358      -0.3   
3    108  서울  2003-01-04     -10.2     -13.4           2356      -6.8   
4    108  서울  2003-01-05     -12.8     -15.5            744      -9.1   
..   ...  ..         ...       ...       ...            ...       ...   
360  108  서울  2003-12-27      -3.0      -6.5            712       1.1   
361  108  서울  2003-12-28       2.3      -2.7            114       6.3   
362  108  서울  2003-12-29       4.2      -0.8           2332       7.5   
363  108  서울  2003-12-30       0.3      -1.8            455       3.0   
364  108  서울  2003-12-31       2.7      -0.3            753       5.8   

     최고기온 시각(hhmi)  
0             1546  
1             1421  
2             1405  
3                0  
4             1556

평균기온(°C)  최저기온(°C)  최고기온(°C)
216      26.0      22.9      32.2

연습 2)

In [ ]:
#1
covid=pd.read_csv('covid.csv')
covid

항목  사례수    증가    감소  변화없음
0    스마트폰  999  78.9   1.7  19.4
1    텔레비전  965  68.5   3.9  27.6
2  개인용 PC  973  65.7   3.7  30.6
3  태블릿 PC  662  46.8   4.2  49.0
4     라디오  687  35.5  12.5  52.0
5    잡지·책  776  31.3  17.8  50.9
6    종이신문  552  17.6  23.2  59.2

In [ ]:
#2
w=covid['사례수']==covid['사례수'].max()
covid[w]

항목  사례수    증가   감소  변화없음
0  스마트폰  999  78.9  1.7  19.4

In [ ]:
#3
covid.sort_values(by='증가',ascending=False)
covid.head(3)

항목  사례수    증가   감소  변화없음
0    스마트폰  999  78.9  1.7  19.4
1    텔레비전  965  68.5  3.9  27.6
2  개인용 PC  973  65.7  3.7  30.6

연습 3)

In [ ]:
#1
vaccine=pd.read_csv('vaccine.csv')
vaccine.tail()

date  subject  day1num  day1sum  day1rate  day2num  day2sum  \
174  2021.04.25  1023346    23323   350631      34.2     3411    18513   
175  2021.04.24  1023346      200   350427      34.2        0    18513   
176  2021.04.23  1027740    10195   345764      33.6      119    18376   
177  2021.04.22  1023538    27074   317386      31.0     2479    15901   
178  2021.04.21  1019322    22501   291857      28.6     2358    13543   

     day2rate  
174       1.8  
175       1.8  
176       1.8  
177       1.6  
178       1.3

In [ ]:
#2
vaccine.drop(['day1sum','day2rate','day2sum','day2rate'],axis=1)

date  subject  day1num  day1rate  day2num
0    2021.10.16  9505868    10673      79.6    66910
1    2021.10.15  9505868    14556      79.4   133580
2    2021.10.14  9505868     9609      79.3    94569
3    2021.10.13  9505868     9804      79.2    77503
4    2021.10.12  9505868    17274      79.1   110204
..          ...      ...      ...       ...      ...
174  2021.04.25  1023346    23323      34.2     3411
175  2021.04.24  1023346      200      34.2        0
176  2021.04.23  1027740    10195      33.6      119
177  2021.04.22  1023538    27074      31.0     2479
178  2021.04.21  1019322    22501      28.6     2358

[179 rows x 5 columns]

In [ ]:
#3
vaccine.describe()

subject        day1num       day1sum    day1rate        day2num  \
count  1.790000e+02     179.000000  1.790000e+02  179.000000     179.000000   
mean   5.086644e+06   40078.150838  3.558876e+06   67.373743   34096.636872   
std    3.324235e+06   44231.469656  2.350423e+06   15.360738   40745.688278   
min    1.019322e+06       0.000000  2.918570e+05   28.600000       0.000000   
25%    2.279241e+06    4385.000000  1.325504e+06   54.650000    4794.500000   
50%    3.943320e+06   23323.000000  3.039867e+06   71.700000   16581.000000   
75%    9.505868e+06   71634.500000  5.469990e+06   79.800000   50950.000000   
max    9.795426e+06  169036.000000  7.562283e+06   95.700000  200186.000000   

            day2sum    day2rate  
count  1.790000e+02  179.000000  
mean   1.827141e+06   28.209497  
std    1.746153e+06   14.998407  
min    1.354300e+04    1.300000  
25%    3.663575e+05   16.050000  
50%    1.226600e+06   29.500000  
75%    3.098630e+06   36.000000  
max    6.191341e+06   65.100000

In [ ]:
#4
print(vaccine.dtypes)# 데이터 타입 확인
vaccine['date']=pd.to_datetime(vaccine['date'])#데이트 형으로 변환
print(vaccine.dtypes)#확인
vaccine['month']=vaccine['date'].dt.month#month열 추가
vaccine.set_index('month',inplace=True)#month를 인덱스로 변경
vaccine.groupby(by='month').mean()#month로 묶은후 평균구하기

date        datetime64[ns]
subject              int64
day1num              int64
day1sum              int64
day1rate           float64
day2num              int64
day2sum              int64
day2rate           float64
dtype: object
date        datetime64[ns]
subject              int64
day1num              int64
day1sum              int64
day1rate           float64
day2num              int64
day2sum              int64
day2rate           float64
dtype: object


date       subject       day1num       day1sum  \
month                                                                 
4     2021-04-25 12:00:00  1.054686e+06  22060.100000  3.860085e+05   
5     2021-05-16 00:00:00  1.289918e+06  18225.548387  6.451063e+05   
6     2021-06-15 12:00:00  3.167106e+06  55957.200000  2.234760e+06   
7     2021-07-16 00:00:00  3.819340e+06  25807.870968  3.064527e+06   
8     2021-08-16 00:00:00  6.702049e+06  57667.258065  4.430462e+06   
9     2021-09-15 12:00:00  9.556825e+06  65715.000000  6.466827e+06   
10    2021-10-08 12:00:00  9.505868e+06   9406.312500  7.486763e+06   

        day1rate       day2num       day2sum   day2rate  
month                                                    
4      36.440000   2304.600000  2.276060e+04   2.140000  
5      51.435484   9734.000000  1.661513e+05  12.529032  
6      69.240000  20147.300000  6.229332e+05  19.276667  
7      80.232258   9934.903226  1.167138e+06  30.467742  
8      72.509677  55575.000000  1.984530e+06  31.080645  
9      67.620000  62162.000000  3.887544e+06  40.663333  
10     78.762500  79900.750000  5.541498e+06  58.343750

In [ ]:
#1
signup=pd.read_csv('signup.csv')
professor=pd.read_csv('professor.csv')
pd.merge(signup,professor)#on을 지정안해도key값이 같은것끼리 묶인다.

수강코드    과목명 담당교수     학과
0   111    파이썬  양숙희  컴퓨터공학
1   222  데이터분석  오경선   인공지능
2   333   인공지능  장은실   정보통신
3   444   선형대수  황복동  컴퓨터공학
4   555   이산수학  정명식   인공지능

In [ ]:
#2
professor.groupby('학과').count()

담당교수
학과         
인공지능      2
정보통신      1
컴퓨터공학     2